apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: restapi-ingress
  labels:
    name: restapi-ingress
  namespace: appdir-namespace
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/health-probe-path: /
    appgw.ingress.kubernetes.io/health-probe-interval: "10s"
    appgw.ingress.kubernetes.io/health-probe-timeout: "10s"
    appgw.ingress.kubernetes.io/health-probe-initial-delay: "10s"
    appgw.ingress.kubernetes.io/health-probe-protocol: "HTTP"
    appgw.ingress.kubernetes.io/health-probe-port: "3000"
spec:
  rules:
  - host: pocvivahealth.com
    http:
      paths:
      - pathType: Exact
        path: "/status"
        backend:
          service:
            name: appdir-service
            port: 
              number: 3000
      
      
